// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'index',
    'installation',
    'quick-start',
    {
      type: 'category',
      label: 'User Guides',
      link: {type: 'doc', id: 'guides/index'},
      items: [
        'guides/architecture',
        'guides/workspace-integration',
        'guides/widgets-and-data',
        'guides/memory-and-recall',
        'guides/multimodal',
        'guides/background-jobs',
        'guides/pywry-chat',
        'guides/getting-started',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Configuration',
      link: {type: 'doc', id: 'operating/index'},
      items: [
        'operating/configuration',
        'operating/profiles',
        'operating/auth',
        'operating/persistence',
        'operating/memory',
        'operating/observability',
      ],
    },
    {
      type: 'category',
      label: 'Developing Plugins',
      link: {type: 'doc', id: 'developing/index'},
      items: [
        'developing/plugin-system',
        'developing/writing-a-tool-source',
        'developing/writing-a-model-provider',
        'developing/writing-a-middleware',
        'developing/writing-a-subagent',
        'developing/writing-an-auth-backend',
        'developing/testing',
      ],
    },
    {
      type: 'category',
      label: 'Explanation',
      link: {type: 'doc', id: 'explanation/index'},
      items: [
        'explanation/wire-contract',
        'explanation/adapter',
        'explanation/canvas',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'reference/index'},
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
  ],
};

export default sidebars;
